################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

###############
### Caching ###
###############
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean compile package install
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonar.klauke-enterprises.com -Dsonar.projectKey=chiara -Dsonar.projectName=chiara -Dsonar.login=$SONAR_TOKEN

##################
### Deployment ###
##################
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    branch: master
    tags: true

###################
### Environment ###
###################
env:
  global:
    - secure: 0prFd3EAcpKa85o1yjqdW1T5jZXnPV0ejWCKkigqzrurFe2nwjYz4faPetdJtD1DZdLW7Y4VvBf7hQx+Fs1rZ6n9XPIDYztDBxB2PCp9sI1k6II7+/TSz1b29OmrJzqlFiVzdxGKQNHbxHtGS2w5QJ/g30MpSTeUzO+fX2OrTBlGXpbvunhev+xOwcHbybI19qgBgsg/U/QX7rodnjBNlbBUSSWbgpXRcFCAbTEBet1f/BbMI2lNdvf8eCQ6hcnOdQ93CGi+BzvZlR7qV24Jhyhi2cTq7bGmxzpFNoCoEEO+d3BkFXn1PoKV8VYEPByrmz1pEuzvGRQmPCaoprdMv4ZEY2RGPihx4E+NLuRvaFSreUOG8flu18B/CTkyW42f1D6TjFB1LttICAd1mtp1VMu08UJg7/7Lo5woGDJUGLRKFOyoMUO/m1CqCqKc9IHCvdeXpVv3DcEDrLx0BnmX0p6dVUeDwrToRm0fHknOnCxg99xK4b9M1rpCeHGbqd+L9nb171Xnhe/AOwXB2GEnkoeH9njedBDlcu4hw6hpf5uqFjhHUFkKw/9vXg4UqKZr2nvmoDypXs0BTJq6pRxAMQhxWmRCoY185HyhQX4uVYOyiLYbl0jr6jtvwhNGT6AVwAoFDRxwG6LAuIBVPKW5c5F5vFfDwtJgSVRisonL2bY=
    - secure: wcjJrDhOOzUdeFXqjJ8chrELhvVSEd+WBqKI6ks6TaVLwut8QZNJoUi66EfubS08FCUq7ISZGo06QEJhmHMfv5QWETOR5ljn5Pm0UvUIV/mfqTzWgcYV6aoKvEP3b7LAvRUwHyHg/e7DVsU8ygGMOWnEb1bcRd7lSaOfy9MbXYYmsIvPQmwFwkUnG4qpmfh2v+Vbs+ZZ5sQmZh0BAvU3V8ljGjN3e5NMPZWoG8PiIpKQDR4V8Cc0wCFX2+PC2npC5+2BeQZbzm9GGdhCso8etsV/fYhOfV61lNiocspeHzEEer6yoTIQyc+F4t0vuaE81vA+rSeLfRSknmRowGPRmNKwMCqZsXiAwnZU09WA2DV0aMMBqXnPtb9Ez6KwI4aAYZ7aisnxGHKC5ZkMYmUPtvVE/zCzDBZrwnxkTfwgYQ885fbHlr6eb95Ag7vxd8OuGoPQe96/oG6Cb38nGaJJF6my9EmSV2hhzFchx9slk3CdCARZOqNzAKHgyPbs3Ztq0qHL46euTc/1MapXSJkP1UAM56C13K7iyZrHxBFaeU8CazZPcskavmc4KzhHBaUNoZ3drGUHEGpDHvCLRtLPeXNHk5VqmQbBatmpGynq2A1Yl8/KIPxgXURtNbylXcyFO7Yd9MNLF4XtIF/tTi2e3GqgjzKdlPVeIgXTwGaao8M=
